import { NextResponse } from "next/server";

export async function GET() {
  const vessels = [
    {
      id: 1,
      name: "MV Pacific Star",
      type: "Container Ship",
      status: "EN ROUTE",
      statusClass: "enroute",
      speed: 21.4,
      heading: 149,
      fuel: 70,
      location: "Singapore",
      lat: -6.2206,
      lng: 106.838,
      accent: "cyan",
    },
    {
      id: 2,
      name: "MV Ocean Voyager",
      type: "Bulk Carrier",
      status: "IN PORT",
      statusClass: "inport",
      speed: 0.0,
      heading: 0,
      fuel: 75,
      location: "Port of Surabaya",
      lat: -7.2165,
      lng: 112.7298,
      accent: "blue",
    },
    {
      id: 3,
      name: "MV Maritime Express",
      type: "Tanker",
      status: "DELAYED",
      statusClass: "delayed",
      speed: -1.1,
      heading: 280,
      fuel: 62,
      location: "Batam Anchorage",
      lat: 1.0456,
      lng: 104.0305,
      accent: "yellow",
    },
    {
      id: 4,
      name: "MV Cargo Master",
      type: "Container Ship",
      status: "MAINTENANCE",
      statusClass: "maintenance",
      speed: 0.0,
      heading: 0,
      fuel: 30,
      location: "Tanjung Priok Dock",
      lat: -6.1048,
      lng: 106.8803,
      accent: "red",
    },
    {
      id: 5,
      name: "MV Nusantara Wave",
      type: "Cargo Vessel",
      status: "EN ROUTE",
      statusClass: "enroute",
      speed: 17.8,
      heading: 96,
      fuel: 66,
      location: "Makassar Strait",
      lat: -2.4,
      lng: 118.1,
      accent: "cyan",
    },
    {
      id: 6,
      name: "MV Eastern Pearl",
      type: "Cargo Vessel",
      status: "EN ROUTE",
      statusClass: "enroute",
      speed: 19.2,
      heading: 121,
      fuel: 81,
      location: "Java Sea",
      lat: -5.8,
      lng: 110.4,
      accent: "cyan",
    },
  ];

  const summary = {
    totalFleet: vessels.length,
    enRoute: vessels.filter((v) => v.statusClass === "enroute").length,
    inPort: vessels.filter((v) => v.statusClass === "inport").length,
    delayed: vessels.filter((v) => v.statusClass === "delayed").length,
    maintenance: vessels.filter((v) => v.statusClass === "maintenance").length,
    selectedVesselId: 1,
    vessels,
    serverTime: new Date().toISOString(),
  };

  return NextResponse.json(summary, {
    headers: {
      "Cache-Control": "no-store, no-cache, must-revalidate, proxy-revalidate",
    },
  });
}