import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    vessels: [
      {
        id: 1,
        name: "Aegir Sentinel",
        type: "Patrol Vessel",
        status: "ACTIVE",
        accent: "cyan",
        speed: 21.4,
        heading: 84,
        fuel: 76,
        lat: -7.8012,
        lng: 110.3649,
        location: "North Sector",
      },
      {
        id: 2,
        name: "Nerida Dawn",
        type: "Cargo Vessel",
        status: "STANDBY",
        accent: "blue",
        speed: 12.8,
        heading: 120,
        fuel: 58,
        lat: -7.7950,
        lng: 110.3700,
        location: "East Corridor",
      },
      {
        id: 3,
        name: "Aquila Tide",
        type: "Research Vessel",
        status: "ACTIVE",
        accent: "yellow",
        speed: 17.2,
        heading: 66,
        fuel: 81,
        lat: -7.8125,
        lng: 110.3520,
        location: "West Survey Line",
      },
      {
        id: 4,
        name: "Orion Wake",
        type: "Support Vessel",
        status: "WARNING",
        accent: "red",
        speed: 9.6,
        heading: 142,
        fuel: 34,
        lat: -7.7884,
        lng: 110.3815,
        location: "Harbor Access",
      },
      {
        id: 5,
        name: "Zephyrus Guard",
        type: "Logistic Vessel",
        status: "OFFLINE",
        accent: "blue",
        speed: 0,
        heading: 0,
        fuel: 49,
        lat: -7.8201,
        lng: 110.3412,
        location: "South Anchorage",
      },
      {
        id: 6,
        name: "Aster Maris",
        type: "Security Vessel",
        status: "ACTIVE",
        accent: "cyan",
        speed: 24.1,
        heading: 101,
        fuel: 67,
        lat: -7.7742,
        lng: 110.3928,
        location: "Outer Patrol Ring",
      },
    ],
  });
}